#' Results of parametric study of the reduction of required sample size to reach
#' 80% statistical power of the treatment effect estimation when using covariate
#' adjustment.
#'
#' The dependence of the reduction on various parameters are studied, for each
#' combination of parameters, the reduction is also compared with various
#' measures of r-squared for time-to-event data.
#'
#' A data frame with 432 rows and 26 columns. Some variables of interest are:
#' \describe{
#'   \item{shape,dropout,t_cutoff,hr_trt,cindex0,lambda0}{Parameters defining a
#'   simulation, see [simu_ph_weibull] and [fix_dist_params()] for details.}
#'   \item{r2_obs_80}{Estimated reduction of required sample size to reach 80%
#'   statistical power}
#'   \item{r2_*,rho_*}{Various r-squared measures for time-to-event data}
#'   ...
#' }
"parametric_study"

#' Results of parametric study of the effect of covariate adjustment and
#' eligibility criteria on the statisitical power of the treatment effect
#' estimation
#'
#' The cohorts are generated by a fully parametric model based on Weibull
#' distribution and proportional hazard model, with a standard normal covariate.
#' Two eligibility criteria based on the quantile of the covariate are studied:
#' 100% and 50%. Two sets of adjustments are studied: no adjustment and
#' adjustment on the standard normal covariate. Together there are four
#' combinations. For each combination, the dependency of the statistical power
#' of the treatment effect estimation on the number of events in the whole trial
#' population is obtained around the 80% power common standard.
#'
#' @format ## `eligibility_parametric`
#' A data frame with 8 columns:
#' \describe{
#'   \item{n_samples}{Number of samples in the whole trial population}
#'   \item{n_events}{Nubmer of events in the whole trial population}
#'   \item{lambda}{Cumulative incidence at 5 years in the control arm}
#'   \item{cindex_base}{Concordance in the control arm when not adjusted on any
#'     covariate}
#'   \item{cindex_adj}{Concordance in the control arm when adjusted on the
#'     standard normal covariate}
#'   \item{power_base}{Statistical power of the treatment effect estimation when
#'     not adjusted on any covariate}
#'   \item{power_adj}{Statistical power of the treatment effect estimation when
#'     adjusted on the standard normal covariate}
#'   \item{inclusion}{Quantile of the standard normal covariate. Samples with
#'     covariate within the quantile are included in the trial.}
#' }
#' @seealso [simu_ph_weibull]
"eligibility_parametric"

#' Results of semi-synthetic study of the effect of covariate adjustment and
#' eligibility criteria on the statisitical power of the treatment effect
#' estimation
#'
#' The cohorts are generated semi-synthetically based on a TCGA dataset.
#' Three eligibility criteria with minimal, intermediate and maximal
#' restrictions are studied, corresponding to 100%, 84% and 55% of the samples
#' in the TCGA dataset. Two sets of adjustment are studied: clinical (`stage`,
#' `ECOG_SCORE`) and clinical + HCC (`stage`, `ECOG_SCORE`, `predOS`), where
#' `predOS` is a prognostic variable coming from a deep model trained with an
#' external dataset. Together there are six combinations. For each combination,
#' the dependency of the statistical power of the treatment effect estimation on
#' the number of events in the whole trial population is obtained around the 80%
#' power common standard.
#'
#' @format ## `eligibility_semisynthetic`
#' A data frame with 8 columns:
#' \describe{
#'   \item{n_samples}{Number of samples in the whole trial population}
#'   \item{n_events}{Nubmer of events in the whole trial population}
#'   \item{lambda}{Cumulative incidence at 5 years in the control arm}
#'   \item{cindex_clinic}{Concordance in the control arm when adjusted on the
#'     clinical group}
#'   \item{cindex_hcc}{Concordance in the control arm when adjusted on the
#'     clinical+HCC group}
#'   \item{power_clinic}{Statistical power of the treatment effect estimation
#'     when adjusted on the clinical group}
#'   \item{power_hcc}{Statistical power of the treatment effect estimation when
#'     adjusted on the clinical+HCC group}
#'   \item{inclusion}{Percentage of patients in the TCGA dataset that are
#'     eligible to be included in the trial}
#' }
"eligibility_semisynthetic"
